/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: bfb83a0206a8d06759edcfecc31a7b36)
interface __BaseEnv_CloudflareEnv {
	NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
	CS35_DB: D1Database;
	NEXT_TAG_CACHE_D1: D1Database;
	IMAGES: ImagesBinding;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ASSETS: Fetcher;
	CS35_DEPLOYMENT_MODE: "staging";
	NEXT_CACHE_DO_QUEUE: DurableObjectNamespace<import("./worker").DOQueueHandler>;
	WORKER_SELF_REFERENCE: Service<typeof import("./worker").default>;
	SCAN_PIPELINE: Workflow<Parameters<import("./worker").ScanPipeline['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "DOQueueHandler";
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CS35_DEPLOYMENT_MODE">> {}
}
