/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 584df8fd801722cf3cf519c1297ebff1)
interface __BaseEnv_CloudflareEnv {
	NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
	CS35_DB: D1Database;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	WORKER_SELF_REFERENCE: Service<typeof import("./.open-next/worker").default>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
