import { restorePublicRequest } from "./cloudflare/ingress";
// OpenNext generates this module during build:cloudflare.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment -- OpenNext module is absent before the first build.
// @ts-ignore generated at build time
import handler from "./.open-next/worker.js";
import type { ExecutionContext } from "@cloudflare/workers-types";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment -- OpenNext module is generated by build.
// @ts-ignore generated at build time
export { DOQueueHandler } from "./.open-next/worker.js";
export { ScanPipeline } from "./workflows/scan-pipeline";

const worker = {
 async fetch(request: Request, env: CloudflareEnv, context: ExecutionContext) {
  const restored = restorePublicRequest(request, env.CS35_GATEWAY_SECRET);
  if (!restored) return new Response("Forbidden", {status: 403});
  request = restored;
  const url = new URL(request.url);
  if (url.hostname === "cs35.ttr.gg") {
   url.hostname = "cybershield35.ttr.gg";
   return new Response(null, {status: 307, headers: {Location: url.toString(), "X-CS35-Deployment": env.CF_VERSION_METADATA.id}});
  }
  const response = await handler.fetch(request, env, context);
  const outgoing = new Response(response.body, response);
  outgoing.headers.set("X-CS35-Deployment", env.CF_VERSION_METADATA.id);
  return outgoing;
 },
 async scheduled() {
  // Old Cron Triggers can propagate after removal. Only the alarm Worker owns jobs.
  console.log("legacy_cron_trigger_ignored");
 },
};

export default worker;
